<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\BrandMasterProduct;
use Illuminate\Support\Facades\DB;

class BrandMasterSeeder extends Seeder
{
    /**
     * Seed central brand master catalog for Plasto Pipes & Fittings.
     */
    public function run(): void
    {
        $products = [
            // ==========================================
            // 1. PLASTO CPVC PIPES (IS: 15778)
            // ==========================================
            [
                'brand_name' => 'Plasto',
                'category_name' => 'CPVC Pipes',
                'item_type' => 'Pipe',
                'product_name' => 'Plasto CPVC Plumbing Pipe SDR-11 (3 Metre) 15mm (1/2")',
                'size_mm' => '15',
                'size_inch' => '1/2"',
                'product_code' => '191',
                'list_price' => 191.00,
                'box_qty' => 80,
                'pouch_qty' => 'Bundle 80',
                'default_gst_percent' => 18.00,
                'hsn_code' => '39172300',
                'image_url' => 'https://images.unsplash.com/photo-1542013936693-884638332954?w=600&auto=format&fit=crop&q=80',
                'description' => 'Plasto CPVC SDR-11 Hot & Cold Potable Water Pipe 3m length.',
            ],
            [
                'brand_name' => 'Plasto',
                'category_name' => 'CPVC Pipes',
                'item_type' => 'Pipe',
                'product_name' => 'Plasto CPVC Plumbing Pipe SDR-11 (3 Metre) 20mm (3/4")',
                'size_mm' => '20',
                'size_inch' => '3/4"',
                'product_code' => '258',
                'list_price' => 258.00,
                'box_qty' => 50,
                'pouch_qty' => 'Bundle 50',
                'default_gst_percent' => 18.00,
                'hsn_code' => '39172300',
                'image_url' => 'https://images.unsplash.com/photo-1542013936693-884638332954?w=600&auto=format&fit=crop&q=80',
                'description' => 'Plasto CPVC SDR-11 Hot & Cold Potable Water Pipe 3m length.',
            ],
            [
                'brand_name' => 'Plasto',
                'category_name' => 'CPVC Pipes',
                'item_type' => 'Pipe',
                'product_name' => 'Plasto CPVC Plumbing Pipe SDR-11 (3 Metre) 25mm (1")',
                'size_mm' => '25',
                'size_inch' => '1"',
                'product_code' => '418',
                'list_price' => 418.00,
                'box_qty' => 30,
                'pouch_qty' => 'Bundle 30',
                'default_gst_percent' => 18.00,
                'hsn_code' => '39172300',
                'image_url' => 'https://images.unsplash.com/photo-1542013936693-884638332954?w=600&auto=format&fit=crop&q=80',
                'description' => 'Plasto CPVC SDR-11 Hot & Cold Potable Water Pipe 3m length.',
            ],
            [
                'brand_name' => 'Plasto',
                'category_name' => 'CPVC Pipes',
                'item_type' => 'Pipe',
                'product_name' => 'Plasto CPVC Plumbing Pipe SDR-11 (3 Metre) 32mm (1 1/4")',
                'size_mm' => '32',
                'size_inch' => '1 1/4"',
                'product_code' => '610',
                'list_price' => 610.00,
                'box_qty' => 20,
                'pouch_qty' => 'Bundle 20',
                'default_gst_percent' => 18.00,
                'hsn_code' => '39172300',
                'image_url' => 'https://images.unsplash.com/photo-1542013936693-884638332954?w=600&auto=format&fit=crop&q=80',
                'description' => 'Plasto CPVC SDR-11 Hot & Cold Potable Water Pipe 3m length.',
            ],
            [
                'brand_name' => 'Plasto',
                'category_name' => 'CPVC Pipes',
                'item_type' => 'Pipe',
                'product_name' => 'Plasto CPVC Plumbing Pipe SDR-11 (3 Metre) 40mm (1 1/2")',
                'size_mm' => '40',
                'size_inch' => '1 1/2"',
                'product_code' => '873',
                'list_price' => 873.00,
                'box_qty' => 15,
                'pouch_qty' => 'Bundle 15',
                'default_gst_percent' => 18.00,
                'hsn_code' => '39172300',
                'image_url' => 'https://images.unsplash.com/photo-1542013936693-884638332954?w=600&auto=format&fit=crop&q=80',
                'description' => 'Plasto CPVC SDR-11 Hot & Cold Potable Water Pipe 3m length.',
            ],
            [
                'brand_name' => 'Plasto',
                'category_name' => 'CPVC Pipes',
                'item_type' => 'Pipe',
                'product_name' => 'Plasto CPVC Plumbing Pipe SDR-11 (3 Metre) 50mm (2")',
                'size_mm' => '50',
                'size_inch' => '2"',
                'product_code' => '1434',
                'list_price' => 1434.00,
                'box_qty' => 10,
                'pouch_qty' => 'Bundle 10',
                'default_gst_percent' => 18.00,
                'hsn_code' => '39172300',
                'image_url' => 'https://images.unsplash.com/photo-1542013936693-884638332954?w=600&auto=format&fit=crop&q=80',
                'description' => 'Plasto CPVC SDR-11 Hot & Cold Potable Water Pipe 3m length.',
            ],

            // ==========================================
            // 2. PLASTO CPVC FITTINGS - ELBOW 90° (IS: 17546)
            // ==========================================
            [
                'brand_name' => 'Plasto',
                'category_name' => 'CPVC Fittings',
                'item_type' => 'Elbow',
                'product_name' => 'Plasto CPVC Plain Elbow 90° 15mm (1/2")',
                'size_mm' => '15',
                'size_inch' => '1/2"',
                'product_code' => '12-7',
                'list_price' => 12.70,
                'box_qty' => 400,
                'pouch_qty' => '100 x 4',
                'default_gst_percent' => 18.00,
                'hsn_code' => '39174000',
                'image_url' => 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&auto=format&fit=crop&q=80',
                'description' => 'Heavy duty Plasto CPVC 90 degree elbow.',
            ],
            [
                'brand_name' => 'Plasto',
                'category_name' => 'CPVC Fittings',
                'item_type' => 'Elbow',
                'product_name' => 'Plasto CPVC Plain Elbow 90° 20mm (3/4")',
                'size_mm' => '20',
                'size_inch' => '3/4"',
                'product_code' => '15-5',
                'list_price' => 15.50,
                'box_qty' => 250,
                'pouch_qty' => '25 x 10',
                'default_gst_percent' => 18.00,
                'hsn_code' => '39174000',
                'image_url' => 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&auto=format&fit=crop&q=80',
                'description' => 'Heavy duty Plasto CPVC 90 degree elbow.',
            ],
            [
                'brand_name' => 'Plasto',
                'category_name' => 'CPVC Fittings',
                'item_type' => 'Elbow',
                'product_name' => 'Plasto CPVC Plain Elbow 90° 25mm (1")',
                'size_mm' => '25',
                'size_inch' => '1"',
                'product_code' => '32-7',
                'list_price' => 32.70,
                'box_qty' => 150,
                'pouch_qty' => '25 x 6',
                'default_gst_percent' => 18.00,
                'hsn_code' => '39174000',
                'image_url' => 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&auto=format&fit=crop&q=80',
                'description' => 'Heavy duty Plasto CPVC 90 degree elbow.',
            ],
            [
                'brand_name' => 'Plasto',
                'category_name' => 'CPVC Fittings',
                'item_type' => 'Elbow',
                'product_name' => 'Plasto CPVC Plain Elbow 90° 32mm (1 1/4")',
                'size_mm' => '32',
                'size_inch' => '1 1/4"',
                'product_code' => '68-1',
                'list_price' => 68.10,
                'box_qty' => 90,
                'pouch_qty' => '15 x 6',
                'default_gst_percent' => 18.00,
                'hsn_code' => '39174000',
                'image_url' => 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&auto=format&fit=crop&q=80',
                'description' => 'Heavy duty Plasto CPVC 90 degree elbow.',
            ],
            [
                'brand_name' => 'Plasto',
                'category_name' => 'CPVC Fittings',
                'item_type' => 'Elbow',
                'product_name' => 'Plasto CPVC Plain Elbow 90° 40mm (1 1/2")',
                'size_mm' => '40',
                'size_inch' => '1 1/2"',
                'product_code' => '125-9',
                'list_price' => 125.90,
                'box_qty' => 50,
                'pouch_qty' => '10 x 5',
                'default_gst_percent' => 18.00,
                'hsn_code' => '39174000',
                'image_url' => 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&auto=format&fit=crop&q=80',
                'description' => 'Heavy duty Plasto CPVC 90 degree elbow.',
            ],
            [
                'brand_name' => 'Plasto',
                'category_name' => 'CPVC Fittings',
                'item_type' => 'Elbow',
                'product_name' => 'Plasto CPVC Plain Elbow 90° 50mm (2")',
                'size_mm' => '50',
                'size_inch' => '2"',
                'product_code' => '280-1',
                'list_price' => 280.10,
                'box_qty' => 22,
                'pouch_qty' => 'Loose',
                'default_gst_percent' => 18.00,
                'hsn_code' => '39174000',
                'image_url' => 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&auto=format&fit=crop&q=80',
                'description' => 'Heavy duty Plasto CPVC 90 degree elbow.',
            ],

            // ==========================================
            // 3. PLASTO CPVC FITTINGS - TEE
            // ==========================================
            [
                'brand_name' => 'Plasto',
                'category_name' => 'CPVC Fittings',
                'item_type' => 'Tee',
                'product_name' => 'Plasto CPVC Equal Tee 15mm (1/2")',
                'size_mm' => '15',
                'size_inch' => '1/2"',
                'product_code' => '17-8',
                'list_price' => 17.80,
                'box_qty' => 250,
                'pouch_qty' => '50 x 5',
                'default_gst_percent' => 18.00,
                'hsn_code' => '39174000',
                'image_url' => 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&auto=format&fit=crop&q=80',
                'description' => 'Plasto CPVC Equal 3-way Tee fitting.',
            ],
            [
                'brand_name' => 'Plasto',
                'category_name' => 'CPVC Fittings',
                'item_type' => 'Tee',
                'product_name' => 'Plasto CPVC Equal Tee 20mm (3/4")',
                'size_mm' => '20',
                'size_inch' => '3/4"',
                'product_code' => '26-1',
                'list_price' => 26.10,
                'box_qty' => 200,
                'pouch_qty' => '25 x 8',
                'default_gst_percent' => 18.00,
                'hsn_code' => '39174000',
                'image_url' => 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&auto=format&fit=crop&q=80',
                'description' => 'Plasto CPVC Equal 3-way Tee fitting.',
            ],
            [
                'brand_name' => 'Plasto',
                'category_name' => 'CPVC Fittings',
                'item_type' => 'Tee',
                'product_name' => 'Plasto CPVC Equal Tee 25mm (1")',
                'size_mm' => '25',
                'size_inch' => '1"',
                'product_code' => '41-8',
                'list_price' => 41.80,
                'box_qty' => 100,
                'pouch_qty' => '25 x 4',
                'default_gst_percent' => 18.00,
                'hsn_code' => '39174000',
                'image_url' => 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&auto=format&fit=crop&q=80',
                'description' => 'Plasto CPVC Equal 3-way Tee fitting.',
            ],
            [
                'brand_name' => 'Plasto',
                'category_name' => 'CPVC Fittings',
                'item_type' => 'Tee',
                'product_name' => 'Plasto CPVC Equal Tee 32mm (1 1/4")',
                'size_mm' => '32',
                'size_inch' => '1 1/4"',
                'product_code' => '83-4',
                'list_price' => 83.40,
                'box_qty' => 60,
                'pouch_qty' => '15 x 4',
                'default_gst_percent' => 18.00,
                'hsn_code' => '39174000',
                'image_url' => 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&auto=format&fit=crop&q=80',
                'description' => 'Plasto CPVC Equal 3-way Tee fitting.',
            ],
            [
                'brand_name' => 'Plasto',
                'category_name' => 'CPVC Fittings',
                'item_type' => 'Tee',
                'product_name' => 'Plasto CPVC Equal Tee 40mm (1 1/2")',
                'size_mm' => '40',
                'size_inch' => '1 1/2"',
                'product_code' => '159-6',
                'list_price' => 159.60,
                'box_qty' => 35,
                'pouch_qty' => '7 x 5',
                'default_gst_percent' => 18.00,
                'hsn_code' => '39174000',
                'image_url' => 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&auto=format&fit=crop&q=80',
                'description' => 'Plasto CPVC Equal 3-way Tee fitting.',
            ],
            [
                'brand_name' => 'Plasto',
                'category_name' => 'CPVC Fittings',
                'item_type' => 'Tee',
                'product_name' => 'Plasto CPVC Equal Tee 50mm (2")',
                'size_mm' => '50',
                'size_inch' => '2"',
                'product_code' => '343-1',
                'list_price' => 343.10,
                'box_qty' => 16,
                'pouch_qty' => '4 x 4',
                'default_gst_percent' => 18.00,
                'hsn_code' => '39174000',
                'image_url' => 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&auto=format&fit=crop&q=80',
                'description' => 'Plasto CPVC Equal 3-way Tee fitting.',
            ],

            // ==========================================
            // 4. PLASTO CPVC FITTINGS - COUPLER (SOCKET)
            // ==========================================
            [
                'brand_name' => 'Plasto',
                'category_name' => 'CPVC Fittings',
                'item_type' => 'Coupler',
                'product_name' => 'Plasto CPVC Plain Coupler / Socket 15mm (1/2")',
                'size_mm' => '15',
                'size_inch' => '1/2"',
                'product_code' => '9-4',
                'list_price' => 9.40,
                'box_qty' => 600,
                'pouch_qty' => '100 x 6',
                'default_gst_percent' => 18.00,
                'hsn_code' => '39174000',
                'image_url' => 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&auto=format&fit=crop&q=80',
                'description' => 'Plasto CPVC pipe connecting socket / coupler.',
            ],
            [
                'brand_name' => 'Plasto',
                'category_name' => 'CPVC Fittings',
                'item_type' => 'Coupler',
                'product_name' => 'Plasto CPVC Plain Coupler / Socket 20mm (3/4")',
                'size_mm' => '20',
                'size_inch' => '3/4"',
                'product_code' => '12-5',
                'list_price' => 12.50,
                'box_qty' => 400,
                'pouch_qty' => '25 x 16',
                'default_gst_percent' => 18.00,
                'hsn_code' => '39174000',
                'image_url' => 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&auto=format&fit=crop&q=80',
                'description' => 'Plasto CPVC pipe connecting socket / coupler.',
            ],
            [
                'brand_name' => 'Plasto',
                'category_name' => 'CPVC Fittings',
                'item_type' => 'Coupler',
                'product_name' => 'Plasto CPVC Plain Coupler / Socket 25mm (1")',
                'size_mm' => '25',
                'size_inch' => '1"',
                'product_code' => '21-3',
                'list_price' => 21.30,
                'box_qty' => 200,
                'pouch_qty' => '25 x 8',
                'default_gst_percent' => 18.00,
                'hsn_code' => '39174000',
                'image_url' => 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&auto=format&fit=crop&q=80',
                'description' => 'Plasto CPVC pipe connecting socket / coupler.',
            ],
            [
                'brand_name' => 'Plasto',
                'category_name' => 'CPVC Fittings',
                'item_type' => 'Coupler',
                'product_name' => 'Plasto CPVC Plain Coupler / Socket 32mm (1 1/4")',
                'size_mm' => '32',
                'size_inch' => '1 1/4"',
                'product_code' => '40-1',
                'list_price' => 40.10,
                'box_qty' => 125,
                'pouch_qty' => '25 x 5',
                'default_gst_percent' => 18.00,
                'hsn_code' => '39174000',
                'image_url' => 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&auto=format&fit=crop&q=80',
                'description' => 'Plasto CPVC pipe connecting socket / coupler.',
            ],
            [
                'brand_name' => 'Plasto',
                'category_name' => 'CPVC Fittings',
                'item_type' => 'Coupler',
                'product_name' => 'Plasto CPVC Plain Coupler / Socket 40mm (1 1/2")',
                'size_mm' => '40',
                'size_inch' => '1 1/2"',
                'product_code' => '75-5',
                'list_price' => 75.50,
                'box_qty' => 75,
                'pouch_qty' => '15 x 5',
                'default_gst_percent' => 18.00,
                'hsn_code' => '39174000',
                'image_url' => 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&auto=format&fit=crop&q=80',
                'description' => 'Plasto CPVC pipe connecting socket / coupler.',
            ],
            [
                'brand_name' => 'Plasto',
                'category_name' => 'CPVC Fittings',
                'item_type' => 'Coupler',
                'product_name' => 'Plasto CPVC Plain Coupler / Socket 50mm (2")',
                'size_mm' => '50',
                'size_inch' => '2"',
                'product_code' => '173-6',
                'list_price' => 173.60,
                'box_qty' => 40,
                'pouch_qty' => '10 x 4',
                'default_gst_percent' => 18.00,
                'hsn_code' => '39174000',
                'image_url' => 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&auto=format&fit=crop&q=80',
                'description' => 'Plasto CPVC pipe connecting socket / coupler.',
            ],

            // ==========================================
            // 5. PLASTO CPVC BRASS FITTINGS (BRASS INSERT)
            // ==========================================
            [
                'brand_name' => 'Plasto',
                'category_name' => 'Brass Fittings',
                'item_type' => 'Brass Elbow',
                'product_name' => 'Plasto CPVC Brass Elbow 90° 15mm x 1/2"',
                'size_mm' => '15',
                'size_inch' => '1/2"',
                'product_code' => '82',
                'list_price' => 82.00,
                'box_qty' => 150,
                'pouch_qty' => '25 x 6',
                'default_gst_percent' => 18.00,
                'hsn_code' => '39174000',
                'image_url' => 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&auto=format&fit=crop&q=80',
                'description' => 'Plasto CPVC Brass Insert Elbow for bib cock / tap fitting.',
            ],
            [
                'brand_name' => 'Plasto',
                'category_name' => 'Brass Fittings',
                'item_type' => 'Brass Elbow',
                'product_name' => 'Plasto CPVC Brass Elbow 90° 20mm x 1/2" (3/4 x 1/2)',
                'size_mm' => '20 x 15',
                'size_inch' => '3/4" x 1/2"',
                'product_code' => '96-3',
                'list_price' => 96.30,
                'box_qty' => 150,
                'pouch_qty' => '25 x 6',
                'default_gst_percent' => 18.00,
                'hsn_code' => '39174000',
                'image_url' => 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&auto=format&fit=crop&q=80',
                'description' => 'Plasto CPVC Brass Insert Reducing Elbow for tap point.',
            ],
            [
                'brand_name' => 'Plasto',
                'category_name' => 'Brass Fittings',
                'item_type' => 'Brass Elbow',
                'product_name' => 'Plasto CPVC Brass Elbow 90° 20mm x 3/4"',
                'size_mm' => '20',
                'size_inch' => '3/4"',
                'product_code' => '129-1',
                'list_price' => 129.10,
                'box_qty' => 75,
                'pouch_qty' => '25 x 3',
                'default_gst_percent' => 18.00,
                'hsn_code' => '39174000',
                'image_url' => 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&auto=format&fit=crop&q=80',
                'description' => 'Plasto CPVC Brass Insert Elbow for heavy plumbing.',
            ],
            [
                'brand_name' => 'Plasto',
                'category_name' => 'Brass Fittings',
                'item_type' => 'Brass Tee',
                'product_name' => 'Plasto CPVC Brass Tee 15mm x 1/2"',
                'size_mm' => '15',
                'size_inch' => '1/2"',
                'product_code' => '85-6',
                'list_price' => 85.60,
                'box_qty' => 150,
                'pouch_qty' => '25 x 6',
                'default_gst_percent' => 18.00,
                'hsn_code' => '39174000',
                'image_url' => 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&auto=format&fit=crop&q=80',
                'description' => 'Plasto CPVC Brass Insert Tee for mixer / shower fitting.',
            ],
            [
                'brand_name' => 'Plasto',
                'category_name' => 'Brass Fittings',
                'item_type' => 'Brass Tee',
                'product_name' => 'Plasto CPVC Brass Tee 20mm x 1/2" (3/4 x 1/2)',
                'size_mm' => '20 x 15',
                'size_inch' => '3/4" x 1/2"',
                'product_code' => '89-1',
                'list_price' => 89.10,
                'box_qty' => 75,
                'pouch_qty' => '25 x 3',
                'default_gst_percent' => 18.00,
                'hsn_code' => '39174000',
                'image_url' => 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&auto=format&fit=crop&q=80',
                'description' => 'Plasto CPVC Brass Insert Reducing Tee.',
            ],
            [
                'brand_name' => 'Plasto',
                'category_name' => 'Brass Fittings',
                'item_type' => 'Brass MTA',
                'product_name' => 'Plasto CPVC MTA Brass 15mm (1/2")',
                'size_mm' => '15',
                'size_inch' => '1/2"',
                'product_code' => '126-1',
                'list_price' => 126.10,
                'box_qty' => 200,
                'pouch_qty' => '25 x 8',
                'default_gst_percent' => 18.00,
                'hsn_code' => '39174000',
                'image_url' => 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&auto=format&fit=crop&q=80',
                'description' => 'Male Threaded Brass Adaptor for CPVC pipes.',
            ],
            [
                'brand_name' => 'Plasto',
                'category_name' => 'Brass Fittings',
                'item_type' => 'Brass MTA',
                'product_name' => 'Plasto CPVC MTA Brass 20mm (3/4")',
                'size_mm' => '20',
                'size_inch' => '3/4"',
                'product_code' => '153-5',
                'list_price' => 153.50,
                'box_qty' => 150,
                'pouch_qty' => '25 x 6',
                'default_gst_percent' => 18.00,
                'hsn_code' => '39174000',
                'image_url' => 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&auto=format&fit=crop&q=80',
                'description' => 'Male Threaded Brass Adaptor for CPVC pipes.',
            ],
            [
                'brand_name' => 'Plasto',
                'category_name' => 'Brass Fittings',
                'item_type' => 'Brass FTA',
                'product_name' => 'Plasto CPVC FTA Brass 15mm (1/2")',
                'size_mm' => '15',
                'size_inch' => '1/2"',
                'product_code' => '93-3',
                'list_price' => 93.30,
                'box_qty' => 150,
                'pouch_qty' => '25 x 6',
                'default_gst_percent' => 18.00,
                'hsn_code' => '39174000',
                'image_url' => 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&auto=format&fit=crop&q=80',
                'description' => 'Female Threaded Brass Adaptor for CPVC pipes.',
            ],
            [
                'brand_name' => 'Plasto',
                'category_name' => 'Brass Fittings',
                'item_type' => 'Brass FTA',
                'product_name' => 'Plasto CPVC FTA Brass 20mm (3/4")',
                'size_mm' => '20',
                'size_inch' => '3/4"',
                'product_code' => '131-4',
                'list_price' => 131.40,
                'box_qty' => 150,
                'pouch_qty' => '25 x 6',
                'default_gst_percent' => 18.00,
                'hsn_code' => '39174000',
                'image_url' => 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&auto=format&fit=crop&q=80',
                'description' => 'Female Threaded Brass Adaptor for CPVC pipes.',
            ],

            // ==========================================
            // 6. PLASTO BALL VALVES
            // ==========================================
            [
                'brand_name' => 'Plasto',
                'category_name' => 'Valves',
                'item_type' => 'Ball Valve',
                'product_name' => 'Plasto CPVC Ball Valve (Compact) 15mm (1/2")',
                'size_mm' => '15',
                'size_inch' => '1/2"',
                'product_code' => '103',
                'list_price' => 103.00,
                'box_qty' => 60,
                'pouch_qty' => '10 x 6',
                'default_gst_percent' => 18.00,
                'hsn_code' => '84818090',
                'image_url' => 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&auto=format&fit=crop&q=80',
                'description' => 'Plasto leak-proof heavy duty CPVC ball valve.',
            ],
            [
                'brand_name' => 'Plasto',
                'category_name' => 'Valves',
                'item_type' => 'Ball Valve',
                'product_name' => 'Plasto CPVC Ball Valve (Compact) 20mm (3/4")',
                'size_mm' => '20',
                'size_inch' => '3/4"',
                'product_code' => '162-2',
                'list_price' => 162.20,
                'box_qty' => 36,
                'pouch_qty' => '12 x 3',
                'default_gst_percent' => 18.00,
                'hsn_code' => '84818090',
                'image_url' => 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&auto=format&fit=crop&q=80',
                'description' => 'Plasto leak-proof heavy duty CPVC ball valve.',
            ],
            [
                'brand_name' => 'Plasto',
                'category_name' => 'Valves',
                'item_type' => 'Ball Valve',
                'product_name' => 'Plasto CPVC Ball Valve (Compact) 25mm (1")',
                'size_mm' => '25',
                'size_inch' => '1"',
                'product_code' => '261-5',
                'list_price' => 261.50,
                'box_qty' => 21,
                'pouch_qty' => '7 x 3',
                'default_gst_percent' => 18.00,
                'hsn_code' => '84818090',
                'image_url' => 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&auto=format&fit=crop&q=80',
                'description' => 'Plasto leak-proof heavy duty CPVC ball valve.',
            ],
            [
                'brand_name' => 'Plasto',
                'category_name' => 'Valves',
                'item_type' => 'Ball Valve',
                'product_name' => 'Plasto CPVC Ball Valve (Compact) 32mm (1 1/4")',
                'size_mm' => '32',
                'size_inch' => '1 1/4"',
                'product_code' => '398',
                'list_price' => 398.00,
                'box_qty' => 12,
                'pouch_qty' => '6 x 2',
                'default_gst_percent' => 18.00,
                'hsn_code' => '84818090',
                'image_url' => 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&auto=format&fit=crop&q=80',
                'description' => 'Plasto leak-proof heavy duty CPVC ball valve.',
            ],

            // ==========================================
            // 7. PLASTO WATER STORAGE TANKS (10-LAYER & 6-LAYER)
            // ==========================================
            [
                'brand_name' => 'Plasto',
                'category_name' => 'Water Storage Tanks',
                'item_type' => 'Water Tank',
                'product_name' => 'Plasto Gold 10-Layer Overhead Water Storage Tank 500 Litres',
                'size_mm' => '500 L',
                'size_inch' => '500 Ltr',
                'product_code' => 'TNK-10L-500',
                'list_price' => 4250.00,
                'box_qty' => 1,
                'pouch_qty' => 'Single Unit',
                'default_gst_percent' => 18.00,
                'hsn_code' => '39251000',
                'image_url' => 'https://images.unsplash.com/photo-1584992236310-6edddc08acff?w=600&auto=format&fit=crop&q=80',
                'description' => 'Plasto Gold 10-Layer 100% Virgin Food Grade UV protected water tank with 10 Years Guarantee.',
            ],
            [
                'brand_name' => 'Plasto',
                'category_name' => 'Water Storage Tanks',
                'item_type' => 'Water Tank',
                'product_name' => 'Plasto Gold 10-Layer Overhead Water Storage Tank 1000 Litres',
                'size_mm' => '1000 L',
                'size_inch' => '1000 Ltr',
                'product_code' => 'TNK-10L-1000',
                'list_price' => 8500.00,
                'box_qty' => 1,
                'pouch_qty' => 'Single Unit',
                'default_gst_percent' => 18.00,
                'hsn_code' => '39251000',
                'image_url' => 'https://images.unsplash.com/photo-1584992236310-6edddc08acff?w=600&auto=format&fit=crop&q=80',
                'description' => 'Plasto Gold 10-Layer 100% Virgin Food Grade UV protected water tank with 10 Years Guarantee.',
            ],
            [
                'brand_name' => 'Plasto',
                'category_name' => 'Water Storage Tanks',
                'item_type' => 'Water Tank',
                'product_name' => 'Plasto 6-Layer Super Cool Double Foam Tank 500 Litres',
                'size_mm' => '500 L',
                'size_inch' => '500 Ltr',
                'product_code' => 'TNK-6L-500',
                'list_price' => 3400.00,
                'box_qty' => 1,
                'pouch_qty' => 'Single Unit',
                'default_gst_percent' => 18.00,
                'hsn_code' => '39251000',
                'image_url' => 'https://images.unsplash.com/photo-1584992236310-6edddc08acff?w=600&auto=format&fit=crop&q=80',
                'description' => 'Plasto 6-Layer Double Foam anti-bacterial insulation water storage tank.',
            ],
            [
                'brand_name' => 'Plasto',
                'category_name' => 'Water Storage Tanks',
                'item_type' => 'Water Tank',
                'product_name' => 'Plasto 6-Layer Super Cool Double Foam Tank 1000 Litres',
                'size_mm' => '1000 L',
                'size_inch' => '1000 Ltr',
                'product_code' => 'TNK-6L-1000',
                'list_price' => 6800.00,
                'box_qty' => 1,
                'pouch_qty' => 'Single Unit',
                'default_gst_percent' => 18.00,
                'hsn_code' => '39251000',
                'image_url' => 'https://images.unsplash.com/photo-1584992236310-6edddc08acff?w=600&auto=format&fit=crop&q=80',
                'description' => 'Plasto 6-Layer Double Foam anti-bacterial insulation water storage tank.',
            ],

            // ==========================================
            // 8. PLASTO SOLVENT CEMENT & ADHESIVES
            // ==========================================
            [
                'brand_name' => 'Plasto',
                'category_name' => 'Adhesives & Solvents',
                'item_type' => 'Adhesive',
                'product_name' => 'Plasto CPVC Heavy Duty Pipe Solvent Cement (Tin) 100ml',
                'size_mm' => '100 ml',
                'size_inch' => '100 ml',
                'product_code' => 'SOL-CPVC-100',
                'list_price' => 65.00,
                'box_qty' => 60,
                'pouch_qty' => 'Tin with dauber',
                'default_gst_percent' => 18.00,
                'hsn_code' => '35061000',
                'image_url' => 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&auto=format&fit=crop&q=80',
                'description' => 'Plasto high-pressure heavy-bodied orange CPVC pipe adhesive.',
            ],
            [
                'brand_name' => 'Plasto',
                'category_name' => 'Adhesives & Solvents',
                'item_type' => 'Adhesive',
                'product_name' => 'Plasto CPVC Heavy Duty Pipe Solvent Cement (Tin) 250ml',
                'size_mm' => '250 ml',
                'size_inch' => '250 ml',
                'product_code' => 'SOL-CPVC-250',
                'list_price' => 145.00,
                'box_qty' => 36,
                'pouch_qty' => 'Tin with dauber',
                'default_gst_percent' => 18.00,
                'hsn_code' => '35061000',
                'image_url' => 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&auto=format&fit=crop&q=80',
                'description' => 'Plasto high-pressure heavy-bodied orange CPVC pipe adhesive.',
            ],
        ];

        foreach ($products as $item) {
            BrandMasterProduct::updateOrCreate(
                [
                    'brand_name' => $item['brand_name'],
                    'product_code' => $item['product_code'],
                ],
                $item
            );
        }
    }
}
