services:
  - type: web
    name: vyaparindia
    env: docker
    plan: free
    region: singapore
    dockerfilePath: Dockerfile
    healthCheckPath: /
    envVars:
      - key: APP_NAME
        value: VyaparIndia
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: true
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: pgsql
      - key: APP_URL
        value: https://www.vyaparindia.online
      - key: SESSION_DOMAIN
        value: .vyaparindia.online
      - key: SESSION_SECURE_COOKIE
        value: "true"
      - key: SESSION_DRIVER
        value: cookie
